name: Build ACRN Package

on:
  workflow_dispatch:
    inputs:
      arch:
        type: choice
        description: which build.
        options: 
        - arm64
        - x86_64
jobs:
  build-orchestrator:
    runs-on: ubuntu-22.04
    steps:
    - name: mkdirs
      run: |
          mkdir acrn-work
    - name: Checkout hypervisor repository
      uses: actions/checkout@v4
      with:
         repository: 'projectacrn/acrn-hypervisor'
         ref: release_3.2
         path: acrn-work/acrn-hypervisor

    - name: Checkout kernel repository
      uses: actions/checkout@v4
      with:
         repository: 'projectacrn/acrn-kernel'
         ref: release_3.2
         path: acrn-work/acrn-kernel

    - name: build deb
      run: debian/debian_build.sh clean && debian/debian_build.sh board_inspector
      working-directory: acrn-work/acrn-hypervisor
    - name: list
      run: ls
      working-directory: acrn-work
