name: Build ACRN Package

on:
  workflow_dispatch:
    inputs:
      arch:
        type: choice
        description: which build.
        options: 
        - arm64
        - x86_64
jobs:
  build-orchestrator:
    runs-on: ubuntu-22.04
    steps:
    - name: mkdirs
      run: |
          mkdir acrn-work
    - name: Checkout hypervisor repository
      uses: actions/checkout@v4
      with:
         repository: 'projectacrn/acrn-hypervisor'
         ref: release_3.2
         path: acrn-work/acrn-hypervisor

    - name: Checkout kernel repository
      uses: actions/checkout@v4
      with:
         repository: 'projectacrn/acrn-kernel'
         ref: release_3.2
         path: acrn-work/acrn-kernel

    - name: install build dependencies    
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
         packages: |
                 gcc git make vim libssl-dev libpciaccess-dev uuid-dev libsystemd-dev libevent-dev 
                 libxml2-dev libxml2-utils libusb-1.0-0-dev python3 python3-pip libblkid-dev 
                 e2fslibs-dev pkg-config libnuma-dev libcjson-dev liblz4-tool 
                 flex bison xsltproc clang-format bc libpixman-1-dev libsdl2-dev 
                 libegl-dev libgles-dev libdrm-dev gnu-efi libelf-dev build-essential git-buildpackage 
                 devscripts dpkg-dev equivs lintian apt-utils pristine-tar dh-python python3-lxml 
                 python3-defusedxml python3-tqdm python3-xmlschema python3-elementpath acpica-tools
         version: 1.0

    - name: build deb
      run: debian/debian_build.sh clean && debian/debian_build.sh board_inspector
      working-directory: acrn-work/acrn-hypervisor
    - name: list
      run: ls
      working-directory: acrn-work
