name: Build ACRN Package

on:
  workflow_dispatch:
    inputs:
      arch:
        type: choice
        description: which build.
        options: 
        - arm64
        - x86_64

jobs:
  build-orchestrator:
    runs-on: ubuntu-22.04
    steps:
    - name: mkdirs
      run: |
          mkdir acrn-work
    - name: list
      run: ls
      working-directory: acrn-work
      
